title:
        O3: 'O$_3$'
        NO2: 'NO$_2$'
        CO: 'CO'
        SO2: 'SO$_2$'
        PM25: 'PM 2.5'
units:
        O3: 'ppbv'
        NO2: 'ppbv'
        CO: 'ppbv'
        SO2: 'ppbv'
        PM25: '$\mu$g/m$^3$'

scale:
        O3: range(10,111,5)
        NO2: '[0.01, 0.02, 0.03, 0.04, 0.07, 0.1, 0.2, 0.3, 0.5, 0.8, 1.3, 2.0, 3.5, 5.0, 10, 15, 25, 40, 60, 100]'
        CO: range(30,256,15)
        SO2: '[0.01, 0.02, 0.03, 0.04, 0.07, 0.1, 0.2, 0.3, 0.5, 0.8, 1.3, 2, 4, 5, 8, 10, 15, 20, 50, 100]'
        PM25: '[1, 2, 3, 5, 8, 10, 20, 25, 30, 40, 50, 60, 80, 90, 100, 150, 200, 300, 400, 500]'

colors:
        O3: "{
            'red':((0.000,0.992,0.992),
               (0.100,0.976,0.976),
               (0.200,0.945,0.945),
               (0.300, 0.906, 0.906),
               (0.400, 0.847, 0.847),
               (0.500, 0.773, 0.773),
               (0.600, 0.682, 0.682),
               (0.700, 0.576, 0.576),
               (0.800, 0.455, 0.455),
               (0.900, 0.318, 0.318),
               (1.000, 0.165, 0.165)),
             'green': ((0.000, 0.953, 0.953),
               (0.100, 0.843, 0.843),
               (0.200, 0.690, 0.690),
               (0.300, 0.525, 0.525),
               (0.400, 0.369, 0.369),
               (0.500, 0.243, 0.243),
               (0.600, 0.149, 0.149),
               (0.700, 0.086, 0.086),
               (0.800, 0.047, 0.047),
               (0.900, 0.008, 0.008),
               (1.000, 0.000, 0.000)),
             'blue':  ((0.000, 0.992, 0.992),
               (0.100, 0.976, 0.976),
               (0.200, 0.945, 0.945),
               (0.300, 0.906, 0.906),
               (0.400, 0.847, 0.847),
               (0.500, 0.773, 0.773),
               (0.600, 0.682, 0.682),
               (0.700, 0.576, 0.576),
               (0.800, 0.455, 0.455),
               (0.900, 0.318, 0.318),
               (1.000, 0.165, 0.165))
        }"

        NO2: "{
         'red': ((0.000, 0.867, 0.867),
           (0.100, 0.729, 0.729),
           (0.200, 0.576, 0.576),
           (0.300, 0.427, 0.427),
           (0.400, 0.298, 0.298),
           (0.500, 0.196, 0.196),
           (0.600, 0.125, 0.125),
           (0.700, 0.075, 0.075),
           (0.800, 0.039, 0.039),
           (0.900, 0.012, 0.012),
           (1.000, 0.000, 0.000)),
         'green': ((0.000, 0.976, 0.976),
           (0.100, 0.953, 0.953),
           (0.200, 0.918, 0.918),
           (0.300, 0.871, 0.871),
           (0.400, 0.808, 0.808),
           (0.500, 0.733, 0.733),
           (0.600, 0.643, 0.643),
           (0.700, 0.541, 0.541),
           (0.800, 0.424, 0.424),
           (0.900, 0.294, 0.294),
           (1.000, 0.157, 0.157)),
         'blue':  ((0.000, 0.867, 0.867),
           (0.100, 0.729, 0.729),
           (0.200, 0.576, 0.576),
           (0.300, 0.427, 0.427),
           (0.400, 0.298, 0.298),
           (0.500, 0.196, 0.196),
           (0.600, 0.122, 0.122),
           (0.700, 0.075, 0.075),
           (0.800, 0.035, 0.035),
           (0.900, 0.008, 0.008),
           (1.000, 0.000, 0.000))
        }"

        hot01: "{
         'red':   ((0.000, 1.000, 1.000),
            (0.250, 1.000, 1.000),
            (0.500, 1.000, 1.000),
            (0.750, 0.886, 0.886),
            (1.000, 0.471, 0.471)),
         'green': ((0.000, 0.973, 0.973),
            (0.250, 0.757, 0.757),
            (0.500, 0.380, 0.380),
            (0.750, 0.067, 0.067),
            (1.000, 0.000, 0.000)),
         'blue':  ((0.000, 0.612, 0.612),
            (0.250, 0.259, 0.259),
            (0.500, 0.106, 0.106),
            (0.750, 0.055, 0.055),
            (1.000, 0.063, 0.063))
        }"
 
        SO2: 'plt.cm.Wistia'

        PM25: 'plt.cm.Oranges'

global:
        colors:
                O3: 'Purples'
                NO2: 'Greens'
                CO: 'hot01'
                SO2: 'Wistia'
                PM25: 'Oranges'
        norm:
                O3: 'None'
                NO2: colors.LogNorm(vmin = 0.01, vmax = 60)
                CO: 'None'
                SO2: colors.LogNorm(vmin=0, vmax= 50)
                PM25: colors.LogNorm(vmin = 1, vmax = 500)
        tick_labels:
                O3: [0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120]
                NO2: [0.01, 0.1, 1, 10, 100]
                CO: [40, 60, 80, 100, 120, 140, 160, 180, 200, 220, 240, 260, 280, 300]
                SO2: [0, .01, .02, .05, .1, .2, .5, 1, 2, 5, 10, 15, 20, 50, 100]
                PM25: [1, 10, 100, 1000]
contour:
        norm:
                O3: 'None'
                NO2: mcolors.BoundaryNorm(bounds, mcmap.N)
                CO: 'None'
                SO2: mcolors.BoundaryNorm(bounds, mcmap.N)
                PM25: mcolors.BoundaryNorm(bounds, mcmap.N)
        cbar_form:
                O3: '%g'
                NO2: '%7.2f'
                CO: '%g'
                SO2: '%7.2f'
                PM25: '%g'
        clab_form:
                O3: '%d'
                NO2: '%.2f'
                CO: '%d'
                SO2: '%.2f'
                PM25: '%d'

bars:
        PM25su_RH35_GCC:
                name: Sulfate
                color: (0.85, 0.9, 0)
                label_pos: -0.11
        PM25ni_RH35_GCC:
                name: Nitrate
                color: (0.04, 0.4, 0.14)
                label_pos: -0.23
        PM25soa_RH35_GCC:
                name: Organics
                color: (1, 0.73, 0)
                label_pos: -0.08
        PM25c_RH35_GCC:
                name: OC + BC
                color: (0, 0, 0)
                label_pos: -0.14
        PM25du_RH35_GCC:
                name: Dust
                color: (1, 0, 0)
                label_pos: -0.17
        PM25ss_RH35_GCC:
                name: Sea Salt
                color: (0, 0, 1)
                label_pos: -0.20


